---
title: "grid_rf"
author: "syh"
date: "June 8, 2017"
output: pdf_document
---

```{r}
# import grid data
grid_data <- read.csv(file = "data/grid_all.csv", stringsAsFactors = F)[,-1]
```

```{r}
# have a look at them
str(grid_data)
head(grid_data)
summary(grid_data)
```


```{r}
# check if there is missing value
# sapply(grid_data, function(x){sum(is.na(x))})
```

```{r}
# let's just use rrate and speed to predict demo
grid_data <- subset(x = grid_data, select = -c(date,hour,grid))
```


```{r}
# let's convert , hour, grid, demo to factors

# grid_data[,"hour"] <- as.factor(grid_data[,"hour"])
# grid_data[,"grid"] <- as.factor(grid_data[,"grid"])
grid_data[,"demo"] <- as.factor(grid_data[,"demo"])
```


```{r}
# as we know that the data is seriously imbalanced
# so we need to deal with this problem by ROSE
library(ROSE)
grid_data <- ROSE(demo ~ ., data = grid_data, p = 0.5, seed = 1)$data
table(grid_data$demo)
```


```{r}
summary(grid_data)
```

```{r}
# for hour, I think we can make it like morning, afternoon, evening
# for grid, we can aggregate them into bigger areas
```

```{r}
# let split data into train and test
set.seed(1)
train_ind <- sample(x = c(1:dim(grid_data)[1]), size = dim(grid_data)[1] * 0.7)

train_data <- grid_data[train_ind,]
test_data <- grid_data[-train_ind,]

# train_x <- train_data[,1:dim(train_data)[2] - 1]
# train_y <- train_data[dim(train_data)[2]]
```


```{r}
# let's first use rpart to train a decision tr
library(rpart)
tree <- rpart(formula = "demo ~. -demo", data = train_data, 
              method = "class", control=rpart.control(cp=0))
```

```{r}
# look at what the tree is like
tree
```

```{r}
# xerror: error in cross validation
# xstd: standard deviation of error in cross vaidation
printcp(tree)
```

```{r}
# let's have a look at complexity parameter against xerror
plotcp(tree)
```

```{r}
# let's find a appropriate cp
cptable <- as.data.frame(tree$cptable)
# opt_cp <- cptable[with(cptable,min(which((xerror - xstd) < min(xerror)))),"CP"]
opt_cp <- cptable[with(cptable, which.min(xerror)),"CP"]
```

```{r}
# prune tree
opt_tree <- prune(tree,cp = opt_cp)
```

```{r}
# let's apply it on test data
est_demo <- predict(object = opt_tree, newdata = test_data)
```

```{r}
# let's check the performance of opt_tre
accuracy.meas(response = test_data$demo, predicted = est_demo[,2], threshold = 0.5)
```

```{r}
# let's look at roc, auc
roc.curve(response = test_data$demo, predicted = est_demo[,2], plotit = T)
```



